name: matten
channels:
  - pytorch
  - conda-forge
  - pyg
  - defaults
dependencies:
  - pytorch>=2.0.0
  - pyg>=2.3.0
  - pytorch-scatter
  - pytorch-lightning>=2.0.0
  - torchmetrics>=0.11.0
  - pymatgen
  - loguru
  - pandas
  - mamba
  - pytest
  - pip:
      - torchtyping
